# Data Preparation and EDA for IoT23 dataset

In [2]:
import os 
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from collections import defaultdict
import csv
from numpy import array
from numpy import argmax
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import time as timer

In [3]:
data= pd.read_csv('iot23_combined_new_3M.csv', low_memory=False)

In [4]:
data.head()  

Unnamed: 0            ts                 uid        id.orig_h  id.orig_p  \
0           0  1.536227e+09  CeqqKl3hyLQmO8LK98  192.168.100.111    17576.0   
1           1  1.536227e+09   C2oHQWo1EFGH8D9x7  192.168.100.111    17576.0   
2           2  1.536227e+09  CJLVjs4BByG04mczXc  192.168.100.111    17576.0   
3           3  1.536227e+09   C0z4uS9AWHDH2s4S7  192.168.100.111    17576.0   
4           4  1.536227e+09  CxbNVk3liFNUIlqSPi  192.168.100.111    17576.0   

        id.resp_h  id.resp_p proto service duration  ... local_orig  \
0    78.1.220.212     8081.0   tcp       -    3e-06  ...          -   
1    152.84.7.111     8081.0   tcp       -    2e-06  ...          -   
2    173.36.41.67     8081.0   tcp       -    2e-06  ...          -   
3    87.13.21.104     8081.0   tcp       -    2e-06  ...          -   
4  99.110.163.140     8081.0   tcp       -    2e-06  ...          -   

  local_resp missed_bytes history orig_pkts  orig_ip_bytes resp_pkts  \
0          -          0.0       S       2.0           80.0       0.0   
1          -          0.0       S       2.0           80.0       0.0   
2          -          0.0       S       2.0           80.0       0.0   
3          -          0.0       S       2.0           80.0       0.0   
4          -          0.0       S       2.0           80.0       0.0   

   resp_ip_bytes    label  detailed_label  
0            0.0  POHScan             NaN  
1            0.0  POHScan             NaN  
2            0.0  POHScan             NaN  
3            0.0  POHScan             NaN  
4            0.0  POHScan             NaN  

[5 rows x 23 columns]

In [5]:
del data['Unnamed: 0']

In [6]:
data.tail()

ts                 uid                 id.orig_h  \
2803565  1.562165e+09  CbiAr234EfpzQInxbg                   0.0.0.0   
2803566  1.562165e+09  CqEhZf1lYmVokqECn3                        ::   
2803567  1.562165e+09  Cr5vKO1CGfMQwFp22c                        ::   
2803568  1.562165e+09  CQ5cJ21U9NUbUWIznd  fe80::5bcc:698e:39d5:cdf   
2803569  1.562165e+09  CjD5ve2qwxfFtvd4zl  fe80::5bcc:698e:39d5:cdf   

         id.orig_p         id.resp_h  id.resp_p proto service  \
2803565       68.0   255.255.255.255       67.0   udp    dhcp   
2803566      143.0          ff02::16        0.0  icmp       -   
2803567      135.0  ff02::1:ffd5:cdf      136.0  icmp       -   
2803568      143.0          ff02::16        0.0  icmp       -   
2803569      133.0           ff02::2      134.0  icmp       -   

                   duration orig_bytes  ... local_orig local_resp  \
2803565           90.034713     3300.0  ...          -          -   
2803566            90.39997      340.0  ...          -          -   
2803567   89.82403000000001       72.0  ...          -          -   
2803568           45.215915      200.0  ...          -          -   
2803569  44.242222999999996        0.0  ...          -          -   

        missed_bytes history  orig_pkts orig_ip_bytes  resp_pkts  \
2803565          0.0       D       11.0        3608.0        0.0   
2803566          0.0       -        9.0         844.0        0.0   
2803567          0.0       -        3.0         216.0        0.0   
2803568          0.0       -        8.0         648.0        0.0   
2803569          0.0       -        2.0          96.0        0.0   

         resp_ip_bytes   label  detailed_label  
2803565            0.0  Benign             NaN  
2803566            0.0  Benign             NaN  
2803567            0.0  Benign             NaN  
2803568            0.0  Benign             NaN  
2803569            0.0  Benign             NaN  

[5 rows x 22 columns]

# Cleaning Process start! 

# dropping unncessary attributes ! 

In [115]:
df= data.drop(columns=['service','history','id.orig_p','id.resp_p','ts','uid','id.orig_h','id.resp_h','local_orig','local_resp','detailed_label'])

In [116]:
df.head()

proto duration orig_bytes resp_bytes conn_state  missed_bytes  orig_pkts  \
0   tcp    3e-06          0          0         S0           0.0        2.0   
1   tcp    2e-06          0          0         S0           0.0        2.0   
2   tcp    2e-06          0          0         S0           0.0        2.0   
3   tcp    2e-06          0          0         S0           0.0        2.0   
4   tcp    2e-06          0          0         S0           0.0        2.0   

   orig_ip_bytes  resp_pkts  resp_ip_bytes    label  
0           80.0        0.0            0.0  POHScan  
1           80.0        0.0            0.0  POHScan  
2           80.0        0.0            0.0  POHScan  
3           80.0        0.0            0.0  POHScan  
4           80.0        0.0            0.0  POHScan

In [117]:
df['orig_bytes'] = df['orig_bytes'].str.replace('-','0')
df['resp_bytes'] = df['resp_bytes'].str.replace('-','0')
df['duration'] = df['duration'].str.replace('-','0')

In [118]:
df.isnull().sum()

proto            0
duration         0
orig_bytes       0
resp_bytes       0
conn_state       0
missed_bytes     0
orig_pkts        0
orig_ip_bytes    0
resp_pkts        0
resp_ip_bytes    0
label            0
dtype: int64

Let us separate the target and independent variables 

okkkk... so there are 7 target variables with very few samples.. we would like to remove all those 

In [12]:
df=df.dropna()

In [119]:
X=df

In [120]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2803570 entries, 0 to 2803569
Data columns (total 11 columns):
 #   Column         Dtype  
---  ------         -----  
 0   proto          object 
 1   duration       object 
 2   orig_bytes     object 
 3   resp_bytes     object 
 4   conn_state     object 
 5   missed_bytes   float64
 6   orig_pkts      float64
 7   orig_ip_bytes  float64
 8   resp_pkts      float64
 9   resp_ip_bytes  float64
 10  label          object 
dtypes: float64(5), object(6)
memory usage: 235.3+ MB


In [121]:
X['orig_bytes']=X['orig_bytes'].astype(float)

In [122]:
X['duration']=X['duration'].astype(float)

In [123]:
X['resp_bytes']=X['resp_bytes'].astype(float)

In [124]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2803570 entries, 0 to 2803569
Data columns (total 11 columns):
 #   Column         Dtype  
---  ------         -----  
 0   proto          object 
 1   duration       float64
 2   orig_bytes     float64
 3   resp_bytes     float64
 4   conn_state     object 
 5   missed_bytes   float64
 6   orig_pkts      float64
 7   orig_ip_bytes  float64
 8   resp_pkts      float64
 9   resp_ip_bytes  float64
 10  label          object 
dtypes: float64(8), object(3)
memory usage: 235.3+ MB


Removing some attack lables as they are very rare .. hence it is better to remove these attacks 

In [125]:
X.drop(X[X['label'] == 'C&C-HeartBeat' ].index, inplace = True)

In [126]:
X.drop(X[X['label'] == 'C&C-Torii' ].index, inplace = True)

In [127]:
X.drop(X[X['label'] == 'Okiru-Attack' ].index, inplace = True)

Separating dependent and independent variables

In [128]:
X=X.iloc[:,:-1]

In [129]:
X.head()

proto   duration  orig_bytes  resp_bytes conn_state  missed_bytes  \
0   tcp  3000000.0         0.0         0.0         S0           0.0   
1   tcp  2000000.0         0.0         0.0         S0           0.0   
2   tcp  2000000.0         0.0         0.0         S0           0.0   
3   tcp  2000000.0         0.0         0.0         S0           0.0   
4   tcp  2000000.0         0.0         0.0         S0           0.0   

   orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  
0        2.0           80.0        0.0            0.0  
1        2.0           80.0        0.0            0.0  
2        2.0           80.0        0.0            0.0  
3        2.0           80.0        0.0            0.0  
4        2.0           80.0        0.0            0.0

In [130]:
y=df['label']

In [151]:
y.head()

0    POHScan
1    POHScan
2    POHScan
3    POHScan
4    POHScan
Name: label, dtype: object

In [132]:
y.value_counts()

POHScan    1324265
Okiru       549228
Benign      472319
DDoS        448703
C&C           8240
Name: label, dtype: int64

let us check the categorical variables

In [133]:
cat_df =X.select_dtypes(include=['object']).copy()

In [134]:
cat_df.head()

proto conn_state
0   tcp         S0
1   tcp         S0
2   tcp         S0
3   tcp         S0
4   tcp         S0

In [135]:
num_df =X.select_dtypes(exclude=['object']).copy()

In [136]:
num_df.head()

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  orig_ip_bytes  \
0  3000000.0         0.0         0.0           0.0        2.0           80.0   
1  2000000.0         0.0         0.0           0.0        2.0           80.0   
2  2000000.0         0.0         0.0           0.0        2.0           80.0   
3  2000000.0         0.0         0.0           0.0        2.0           80.0   
4  2000000.0         0.0         0.0           0.0        2.0           80.0   

   resp_pkts  resp_ip_bytes  
0        0.0            0.0  
1        0.0            0.0  
2        0.0            0.0  
3        0.0            0.0  
4        0.0            0.0

ok so there are only three categorical variables...

In [137]:
le=LabelEncoder()

In [138]:
enc_df =cat_df.apply(LabelEncoder().fit_transform)

In [139]:
enc_df.head()

proto  conn_state
0      1           6
1      1           6
2      1           6
3      1           6
4      1           6

In [140]:
Xe=pd.concat([num_df,enc_df], axis=1)

In [141]:
Xe.head()

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  orig_ip_bytes  \
0  3000000.0         0.0         0.0           0.0        2.0           80.0   
1  2000000.0         0.0         0.0           0.0        2.0           80.0   
2  2000000.0         0.0         0.0           0.0        2.0           80.0   
3  2000000.0         0.0         0.0           0.0        2.0           80.0   
4  2000000.0         0.0         0.0           0.0        2.0           80.0   

   resp_pkts  resp_ip_bytes  proto  conn_state  
0        0.0            0.0      1           6  
1        0.0            0.0      1           6  
2        0.0            0.0      1           6  
3        0.0            0.0      1           6  
4        0.0            0.0      1           6

In [142]:
Xe.head()

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  orig_ip_bytes  \
0  3000000.0         0.0         0.0           0.0        2.0           80.0   
1  2000000.0         0.0         0.0           0.0        2.0           80.0   
2  2000000.0         0.0         0.0           0.0        2.0           80.0   
3  2000000.0         0.0         0.0           0.0        2.0           80.0   
4  2000000.0         0.0         0.0           0.0        2.0           80.0   

   resp_pkts  resp_ip_bytes  proto  conn_state  
0        0.0            0.0      1           6  
1        0.0            0.0      1           6  
2        0.0            0.0      1           6  
3        0.0            0.0      1           6  
4        0.0            0.0      1           6

In [159]:
Ye=le.fit_transform(y)

In [145]:
from sklearn.preprocessing import MinMaxScaler

In [154]:
scaler = MinMaxScaler()
scaler.fit(Xe)

MinMaxScaler()

In [155]:
normalized_x = scaler.transform(Xe)
normalized_x

array([[3.33333333e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e-01, 5.00000000e-01],
       [2.22222222e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e-01, 5.00000000e-01],
       [2.22222222e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e-01, 5.00000000e-01],
       ...,
       [9.98044778e-06, 7.48170699e-08, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.02399056e-06, 2.07825194e-07, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.91580256e-06, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [171]:
scaling=StandardScaler()

In [172]:
Xs=scaling.fit_transform(Xe)

In [173]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import neighbors
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import learning_curve
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import auc,roc_auc_score,roc_curve,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

In [187]:
X_train, X_test, Y_train, Y_test = train_test_split(Xs, Ye, random_state=124, test_size=0.20, shuffle=True)

In [175]:
X_train=scaling.fit_transform(X_train)

In [61]:
X_test=scaling.fit_transform(X_test)

In [62]:
X_train.shape

(1681653, 12)

In [63]:
X_test.shape

(1121102, 12)

In [64]:
Y_train.shape

(1681653,)

In [65]:
Y_test.shape

(1121102,)

In [120]:
train_scores, test_scores = list(), list()
values = [i for i in range(1, 15)]

In [121]:
for i in values:
	# configure the model
	model = DecisionTreeClassifier(max_depth=i)
	# fit model on the training dataset
	model.fit(X_train, Y_train)
	# evaluate on the train dataset
	train_yhat = model.predict(X_train)
	train_acc = accuracy_score(Y_train, train_yhat)
	train_scores.append(train_acc)
	# evaluate on the test dataset
	test_yhat = model.predict(X_test)
	test_acc = accuracy_score(Y_test, test_yhat)
	test_scores.append(test_acc)
	# summarize progress
	print('>%d, train: %.3f, test: %.3f' % (i, train_acc, test_acc))

>1, train: 0.626, test: 0.625
>2, train: 0.768, test: 0.768
>3, train: 0.768, test: 0.768
>4, train: 0.768, test: 0.768
>5, train: 0.768, test: 0.768
>6, train: 0.768, test: 0.768
>7, train: 0.768, test: 0.768
>8, train: 0.768, test: 0.768
>9, train: 0.768, test: 0.768
>10, train: 0.768, test: 0.768
>11, train: 0.768, test: 0.768
>12, train: 0.768, test: 0.768
>13, train: 0.768, test: 0.768
>14, train: 0.768, test: 0.768


The model is either underfitting or overfitting there is something wrong with Data! 

In [188]:
start = timer.time()
gnb_model = GaussianNB()
gnb_model.fit(X_train, Y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.81 seconds


In [189]:
# Predicting the train set results
y_gnbr = gnb_model.predict(X_train)


In [190]:
print("Accuracy score for GNB: {:.4f}".format(accuracy_score(Y_train,y_gnbr)))

Accuracy score for GNB: 0.4928


In [191]:
# Predicting the test set results
y_gnb = gnb_model.predict(X_test)
y_gnb_prob = gnb_model.predict_proba(X_test)

In [192]:
print("Classification report for GNB: \n{}".format(classification_report(Y_test,y_gnb)))
print("Confusion matrix for GNB: \n{}".format(confusion_matrix(Y_test,y_gnb)))
print("Accuracy score for GNB: {:.4f}".format(accuracy_score(Y_test,y_gnb)))
# calculate precision, recall, and f1 scores
prec_gnb = precision_score(Y_test,y_gnb,average='weighted')
rec_gnb = recall_score(Y_test,y_gnb,average='weighted')
f1_gnb = f1_score(Y_test,y_gnb,average='weighted')
print("Precision score for GNB: {:.2f}".format(prec_gnb))
print("Recall score for GNB: {:.2f}".format(rec_gnb))
print("F1 score for GNB: {:.2f}".format(f1_gnb))

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification report for GNB: 
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     94504
           1       0.00      0.00      0.00      1588
           2       1.00      0.89      0.94     89803
           3       0.28      1.00      0.44    109985
           4       0.88      0.00      0.01    264671

    accuracy                           0.49    560551
   macro avg       0.63      0.56      0.47    560551
weighted avg       0.80      0.49      0.40    560551

Confusion matrix for GNB: 
[[ 85938      0     50   8401    115]
 [     1      0      0   1587      0]
 [     6      0  79875   9922      0]
 [    15      0      0 109969      1]
 [  1645      0      4 262136    886]]
Accuracy score for GNB: 0.4936


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precision score for GNB: 0.80
Recall score for GNB: 0.49
F1 score for GNB: 0.40


In [193]:
start = timer.time()
DT_clf= DecisionTreeClassifier()
DT_clf.fit(X_train,Y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 3.29 seconds


In [194]:
y_DTr = DT_clf.predict(X_train)

In [195]:
print("Accuracy score for DT: {:.4f}".format(accuracy_score(Y_train,y_DTr)))

Accuracy score for DT: 0.7681


In [196]:
y_DT = DT_clf.predict(X_test)
y_DT_prob = DT_clf.predict_proba(X_test)

In [197]:
print("Classification report for DT: \n{}".format(classification_report(Y_test,y_DT)))
print("Confusion matrix for DT: \n{}".format(confusion_matrix(Y_test,y_DT)))
print("Accuracy score for DT: {:.4f}".format(accuracy_score(Y_test,y_DT)))

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification report for DT: 
              precision    recall  f1-score   support

           0       1.00      0.91      0.95     94504
           1       0.00      0.00      0.00      1588
           2       1.00      0.89      0.94     89803
           3       0.00      0.00      0.00    109985
           4       0.67      1.00      0.80    264671

    accuracy                           0.77    560551
   macro avg       0.53      0.56      0.54    560551
weighted avg       0.65      0.77      0.69    560551

Confusion matrix for DT: 
[[ 85973      0     30      1   8500]
 [     1      0      0      0   1587]
 [     5      0  79876      0   9922]
 [    16      0      0      0 109969]
 [    10      0      0      0 264661]]
Accuracy score for DT: 0.7680


In [130]:
from collections import Counter

In [131]:
print('Original dataset shape %s' % Counter(Ye))

Original dataset shape Counter({4: 1324265, 3: 549228, 0: 472319, 2: 448703, 1: 8240})


In [125]:
from imblearn import under_sampling, over_sampling

In [128]:
from imblearn.under_sampling import RandomUnderSampler

In [150]:
rus=RandomUnderSampler(sampling_strategy='majority',random_state=21)

In [151]:
X_res, y_res = rus.fit_resample(Xe, Ye)

In [152]:
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({3: 549228, 0: 472319, 2: 448703, 1: 8240, 4: 8240})


Followed by oversampling

In [153]:
from imblearn.over_sampling import RandomOverSampler

In [154]:
over = RandomOverSampler(sampling_strategy='minority')

In [157]:
X_rs, y_rs = over.fit_resample(X_res, y_res)

In [158]:
print('Resampled dataset shape %s' % Counter(y_rs))

Resampled dataset shape Counter({1: 549228, 3: 549228, 0: 472319, 2: 448703, 4: 8240})


In [159]:
X_train, X_test, Y_train, Y_test = train_test_split(X_res, y_res, random_state=10, test_size=0.20)

In [160]:
train_scores, test_scores = list(), list()
values = [i for i in range(1, 15)]