# Data Preparation and EDA for IoT23 dataset

In [8]:
import os 
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from collections import defaultdict
import csv
from numpy import array
from numpy import argmax
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import time as timer

In [9]:
data= pd.read_csv('D:\JupyterNotebook\GitHub\IoT-BotNet-detection-on-IoT23-dataset\IoT23\Data files\clean_data.csv', low_memory=False)

In [10]:
data.head()

Unnamed: 0            ts  id.orig_p  id.resp_p proto service   duration  \
0       98304  1.536227e+09    17832.0    37215.0   tcp       -  2000000.0   
1       98305  1.536227e+09    17832.0    37215.0   tcp       -  2000000.0   
2       98306  1.536227e+09    17832.0    37215.0   tcp       -  6000000.0   
3       98307  1.536227e+09    17832.0    37215.0   tcp       -  2000000.0   
4       98308  1.536227e+09    17832.0    37215.0   tcp       -  2000000.0   

   orig_bytes  resp_bytes conn_state  missed_bytes history  orig_pkts  \
0         0.0         0.0         S0           0.0       S        2.0   
1         0.0         0.0         S0           0.0       S        2.0   
2         0.0         0.0         S0           0.0       S        2.0   
3         0.0         0.0         S0           0.0       S        2.0   
4         0.0         0.0         S0           0.0       S        2.0   

   orig_ip_bytes  resp_pkts  resp_ip_bytes  label  
0           80.0        0.0            0.0  Okiru  
1           80.0        0.0            0.0  Okiru  
2           80.0        0.0            0.0  Okiru  
3           80.0        0.0            0.0  Okiru  
4           80.0        0.0            0.0  Okiru

In [11]:
del data['Unnamed: 0']

In [12]:
df= data.drop(columns=['service','ts','id.orig_p','id.resp_p'], inplace=True)

In [13]:
df=data

In [14]:
df.head()

proto   duration  orig_bytes  resp_bytes conn_state  missed_bytes history  \
0   tcp  2000000.0         0.0         0.0         S0           0.0       S   
1   tcp  2000000.0         0.0         0.0         S0           0.0       S   
2   tcp  6000000.0         0.0         0.0         S0           0.0       S   
3   tcp  2000000.0         0.0         0.0         S0           0.0       S   
4   tcp  2000000.0         0.0         0.0         S0           0.0       S   

   orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  label  
0        2.0           80.0        0.0            0.0  Okiru  
1        2.0           80.0        0.0            0.0  Okiru  
2        2.0           80.0        0.0            0.0  Okiru  
3        2.0           80.0        0.0            0.0  Okiru  
4        2.0           80.0        0.0            0.0  Okiru

In [13]:
#df= data.drop(columns=['ts','id.orig_p','id.resp_p'])

In [15]:
X= df.iloc[:,:-1]

In [16]:
Y=df['label'] 

In [17]:
X.head()

proto   duration  orig_bytes  resp_bytes conn_state  missed_bytes history  \
0   tcp  2000000.0         0.0         0.0         S0           0.0       S   
1   tcp  2000000.0         0.0         0.0         S0           0.0       S   
2   tcp  6000000.0         0.0         0.0         S0           0.0       S   
3   tcp  2000000.0         0.0         0.0         S0           0.0       S   
4   tcp  2000000.0         0.0         0.0         S0           0.0       S   

   orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  
0        2.0           80.0        0.0            0.0  
1        2.0           80.0        0.0            0.0  
2        2.0           80.0        0.0            0.0  
3        2.0           80.0        0.0            0.0  
4        2.0           80.0        0.0            0.0

In [19]:
cat_df =X.select_dtypes(include=['object']).copy()

In [20]:
num_df =X.select_dtypes(exclude=['object']).copy()

In [21]:
encode_all_cat =cat_df.apply(LabelEncoder().fit_transform)

In [22]:
encode_all_cat.head()

proto  conn_state  history
0      1           4       11
1      1           4       11
2      1           4       11
3      1           4       11
4      1           4       11

In [23]:
encoded_data =pd.concat([num_df,encode_all_cat], axis=1)

In [24]:
encoded_data.head()

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  orig_ip_bytes  \
0  2000000.0         0.0         0.0           0.0        2.0           80.0   
1  2000000.0         0.0         0.0           0.0        2.0           80.0   
2  6000000.0         0.0         0.0           0.0        2.0           80.0   
3  2000000.0         0.0         0.0           0.0        2.0           80.0   
4  2000000.0         0.0         0.0           0.0        2.0           80.0   

   resp_pkts  resp_ip_bytes  proto  conn_state  history  
0        0.0            0.0      1           4       11  
1        0.0            0.0      1           4       11  
2        0.0            0.0      1           4       11  
3        0.0            0.0      1           4       11  
4        0.0            0.0      1           4       11

In [25]:
encoded_data.shape

(393750, 11)

In [26]:
Xe=encoded_data

In [27]:
Xe = np.asarray(Xe).astype(np.float32)

In [28]:
print(Xe)

[[2.0e+06 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]
 [2.0e+06 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]
 [6.0e+06 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]
 ...
 [0.0e+00 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]
 [0.0e+00 0.0e+00 0.0e+00 ... 1.0e+00 4.0e+00 1.1e+01]]


In [29]:
Y.head()

0    Okiru
1    Okiru
2    Okiru
3    Okiru
4    Okiru
Name: label, dtype: object

In [30]:
le=LabelEncoder()

In [31]:
encoder=LabelEncoder()
encoder.fit(Y)
y=encoder.transform(Y)
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7])

# Standard Scaling ...! 

In [32]:
scaling=StandardScaler()

In [33]:
X_sc=scaling.fit_transform(Xe)

In [34]:
X_sc.shape

(393750, 11)

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import neighbors
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import roc_auc_score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import auc,roc_auc_score,roc_curve,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

In [36]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5, random_state=None)

In [37]:
model = LogisticRegression()

In [38]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(model, X_sc, y, scoring=score, cv=10, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(


Finished training within 98.57 seconds


In [39]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [40]:
print(np.mean(scores['test_f1_macro']))

0.40191654172282565


In [41]:
print(np.mean(scores['test_accuracy']))

0.5084571428571427


In [42]:
print(np.mean(scores['test_precision_macro']))

0.5161176078808966


In [43]:
print(np.mean(scores['test_recall_macro']))

0.42161727519998726


# Gussian Naive Bayes

In [44]:
gnb_model = GaussianNB()

In [45]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(gnb_model, X_sc, y, scoring=score, cv=5, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.79 seconds


In [46]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [47]:
print(np.mean(scores['test_accuracy']))

0.055169523809523814


In [48]:
print(np.mean(scores['test_recall_macro']))

0.411120670049942


In [49]:
print(np.mean(scores['test_precision_macro']))

0.4800980775831006


In [50]:
print(np.mean(scores['test_f1_macro']))

0.28933328356149474


# Random Forest Classifier

In [51]:
Rf_clf=RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state =124)

In [52]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(Rf_clf, X_sc, y, scoring=score, cv=5, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 72.45 seconds


In [53]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [54]:
print(np.mean(scores['test_accuracy']))

0.6581434920634921


In [55]:
print(np.mean(scores['test_recall_macro']))

0.51855253947357


In [56]:
print(np.mean(scores['test_precision_macro']))

0.693420396777851


In [57]:
print(np.mean(scores['test_f1_macro']))

0.4785656762806919


Decision Tree classifier 

In [58]:
DT_clf= DecisionTreeClassifier()

In [59]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(DT_clf, X_sc, y, scoring=score, cv=5, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.92 seconds


In [60]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [61]:
print("Test Accuracy:", np.mean(scores['test_accuracy']))
print("Recall score: ", np.mean(scores['test_recall_macro']))
print("Precision score: ", np.mean(scores['test_precision_macro']))
print("F1-score: ", np.mean(scores['test_f1_macro']))

Test Accuracy: 0.6581282539682538
Recall score:  0.5060469045278909
Precision score:  0.686608707583205
F1-score:  0.46509853583180405


# XGB Classifier! 

In [62]:
xgb_model = XGBClassifier()

In [63]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(xgb_model, X_sc, y, scoring=score, cv=5, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 178.78 seconds


In [64]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [65]:
print("Test Accuracy:", np.mean(scores['test_accuracy']))
print("Recall score: ", np.mean(scores['test_recall_macro']))
print("Precision score: ", np.mean(scores['test_precision_macro']))
print("F1-score: ", np.mean(scores['test_f1_macro']))

Test Accuracy: 0.6580926984126984
Recall score:  0.5184957981028825
Precision score:  0.7000886331422318
F1-score:  0.4835227123678688


# KNN Model

In [66]:
knn_model = neighbors.KNeighborsClassifier()

In [67]:
start = timer.time()
score = ['precision_macro', 'recall_macro','accuracy','f1_macro']
scores = cross_validate(knn_model, X_sc, y, scoring=score, cv=5, n_jobs=-1)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 462.97 seconds


In [68]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_accuracy',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro']

In [69]:
print("Test Accuracy:", np.mean(scores['test_accuracy']))
print("Recall score: ", np.mean(scores['test_recall_macro']))
print("Precision score: ", np.mean(scores['test_precision_macro']))
print("F1-score: ", np.mean(scores['test_f1_macro']))

Test Accuracy: 0.39392761904761897
Recall score:  0.5346972611828364
Precision score:  0.45244632140642765
F1-score:  0.34181927414740304
